name: Atualizador de Dados do Double

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Fetch API and Update History
        id: update_script
        run: |
          node -e "
            const fs = require('fs').promises;
            const path = require('path');
            
            const HISTORY_FILE_PATH = path.join(__dirname, 'history.json');
            const BLAZE_API_URL = 'https://blaze.com/api/roulette_games/recent'; 
            const HISTORY_MAX_LENGTH = 480;

            async function run() {
              try {
                console.log('Buscando dados da API da Blaze...');
                const response = await fetch(BLAZE_API_URL);
                if (!response.ok) {
                  throw new Error(`Falha na API: Status ${response.status}`);
                }
                const apiData = await response.json();

                if (!apiData || !Array.isArray(apiData) || apiData.length === 0) {
                  throw new Error('Resposta da API inválida ou vazia.');
                }
                
                const lastApiRollId = apiData[apiData.length - 1].id;

                let currentData = { history: [], lastId: null };

                try {
                  const historyFileContent = await fs.readFile(HISTORY_FILE_PATH, 'utf8');
                  // O arquivo history.json só terá o array, então tratamos assim
                  const savedHistory = JSON.parse(historyFileContent);
                  if (Array.isArray(savedHistory)) {
                      currentData.history = savedHistory;
                  }
                } catch (e) {
                  console.log('Arquivo de histórico não encontrado ou inválido. Será criado um novo.');
                }

                // Lógica simplificada: Se o último número do histórico salvo for igual ao último da API, não faz nada
                const lastApiRollNumber = apiData[apiData.length - 1].roll;
                if (currentData.history.length > 0 && currentData.history[currentData.history.length - 1] === lastApiRollNumber) {
                     console.log('Nenhum resultado novo detectado. Finalizando.');
                     return process.stdout.write('::set-output name=updated::false\n');
                }

                console.log('Novos resultados encontrados! Atualizando...');
                const allValidRolls = apiData.filter(roll => roll.roll !== 0).map(roll => roll.roll);
                const newHistory = allValidRolls.slice(-HISTORY_MAX_LENGTH);

                await fs.writeFile(HISTORY_FILE_PATH, JSON.stringify(newHistory, null, 2), 'utf8');
                console.log(`Histórico atualizado. Total de ${newHistory.length} rodadas.`);
                return process.stdout.write('::set-output name=updated::true\n');

              } catch (error) {
                console.error('Erro durante a execução do script:', error);
                process.exit(1);
              }
            }

            run();
          "

      - name: Commit and push changes
        if: steps.update_script.outputs.updated == 'true'
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add history.json
          git commit -m "chore(data): Atualiza histórico do Double"
          git push
