name: Atualizador de Dados do Double

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      - name: Setup do Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Busca API e Atualiza Histórico
        id: update_script
        run: |
          node -e "
            const fs = require('fs').promises;
            const path = require('path');
            
            const HISTORY_FILE_PATH = path.join(__dirname, 'history.json');
            const BLAZE_API_URL = 'https://blaze.com/api/roulette_games/recent'; 
            const HISTORY_MAX_LENGTH = 480;

            async function run() {
              try {
                console.log('Buscando dados da API da Blaze...');
                const response = await fetch(BLAZE_API_URL);

                if (!response.ok) {
                  // Mensagem de erro sem caracteres problemáticos
                  console.error('Falha na API: Status ' + response.status);
                  process.exit(1);
                }
                
                const apiData = await response.json();

                if (!apiData || !Array.isArray(apiData) || apiData.length === 0) {
                  throw new Error('Resposta da API invalida ou vazia.');
                }
                
                let history = [];
                try {
                  const historyFileContent = await fs.readFile(HISTORY_FILE_PATH, 'utf8');
                  const savedHistory = JSON.parse(historyFileContent);
                  if (Array.isArray(savedHistory)) {
                      history = savedHistory;
                  }
                } catch (e) {
                  console.log('Arquivo de historico nao encontrado. Sera criado um novo.');
                }

                const newHistory = apiData
                  .filter(roll => roll.roll !== 0) // Filtra os brancos
                  .map(roll => roll.roll) // Pega apenas os números
                  .slice(-HISTORY_MAX_LENGTH); // Limita ao máximo de 480

                // Compara as strings JSON para ver se houve mudança
                if (JSON.stringify(history) === JSON.stringify(newHistory)) {
                    console.log('Nenhum resultado novo detectado. Finalizando.');
                    return process.stdout.write('::set-output name=updated::false\n');
                }

                console.log('Novos resultados encontrados! Atualizando historico...');
                await fs.writeFile(HISTORY_FILE_PATH, JSON.stringify(newHistory, null, 2), 'utf8');
                
                // Mensagem de sucesso sem caracteres problemáticos
                console.log('Historico atualizado. Total de ' + newHistory.length + ' rodadas.');
                return process.stdout.write('::set-output name=updated::true\n');

              } catch (error) {
                console.error('Erro durante a execucao do script:', error);
                process.exit(1);
              }
            }
            
            run();
          "

      - name: Commit e Push das mudanças
        if: steps.update_script.outputs.updated == 'true'
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add history.json
          git commit -m "chore(data): Atualiza histórico do Double"
          git push
